### ISSUE TITLE
Can't get it working at all

### ISSUE THREAD

**Issue by markaabo** [Dessie0/TwitchMinecraftSync#1]
I cant seem to get the plugin working at all

I have set the correct client ID and channel name, ive even recreated the aplication multiple times with different ids and secrets, ive triple checked everything and just can't get it working, it always displays this messages:
`[18:10:54 ERROR]: [TwitchMinecraftSync] Invalid Twitch channel name or Client ID.`

**Comment by markaabo** [comment]
@Dessie0 Would it be possible to make the plugin work again, and update it to Java 16+ so it would work with minecraft 1.18

No other plugin seems to be updated or working covering the feature of giving subs roles, only one other plugin has it working with 1.18 but that plugin only works if a sub subs doing a stream and is logged onto the server at the same time :(

**Comment by Dessie0** [comment]
> @Dessie0 Would it be possible to make the plugin work again, and update it to Java 16+ so it would work with minecraft 1.18
> 
> No other plugin seems to be updated or working covering the feature of giving subs roles, only one other plugin has it working with 1.18 but that plugin only works if a sub subs doing a stream and is logged onto the server at the same time :(

This error can only happen if there's an issue requesting the initial channel data from Twitch. Make sure the channel name you're putting in the config.yml is all lowercase and that the client ID and client secret are correct and match to the same Twitch Application.

**Comment by markaabo** [comment]
@Dessie0 I've now tried setting the name all lowercase, and it still does not work. it says the same, and I've also tried creating a new application and triple checked the client ID and the secret, its correct but it still gives me the error

The channel name is "Swind3ls" on twitch, and in the config i put it as "swind3ls".

**Comment by Dessie0** [comment]
> @Dessie0 I've now tried setting the name all lowercase, and it still does not work. it says the same, and I've also tried creating a new application and triple checked the client ID and the secret, its correct but it still gives me the error
> 
> The channel name is "Swind3ls" on twitch, and in the config i put it as "swind3ls".

Interesting, I'm not sure what would be causing that then. Fortunately, Twitch is removing legacy API so I'll need to update the plugin to support their new API fairly soon. I'll be sure this is resolved when that's done.

**Comment by sameethan1** [comment]
I was just looking for a sub sync plugin, surprised there aren't any really and yours is the newest/sounds like you are still willing to update it. I was testing it out and ran into the same issue as Mark, though my name/id/secret are correct, it always gives the error. Hoping you can update it, really looking forward to using it.

**Comment by Dessie0** [comment]
@sameethan1 @markaabo A hotfix has been pushed to hopefully resolve this issue. 

You can download the new version at https://github.com/Dessie0/TwitchMinecraftSync/packages/772076 (Link is on the right side, I'll make a full release when the re-write is completed. The correct one is twitchminecraftsync-1.2.2-all.jar)

Please note the commit changes, as Resubscribe features a little wonky (due to Twitch changes).
Also, a full re-write of this plugin is expected soon, but hopefully this atleast fixes the issue you're having so you can start getting basic functionality working.

**Comment by sameethan1** [comment]
> @sameethan1 @markaabo A hotfix has been pushed to hopefully resolve this issue.
> 
> You can download the new version at https://github.com/Dessie0/TwitchMinecraftSync/packages/772076 (Link is on the right side, I'll make a full release when the re-write is completed. The correct one is twitchminecraftsync-1.2.2-all.jar)
> 
> Please note the commit changes, as Resubscribe features a little wonky (due to Twitch changes). Also, a full re-write of this plugin is expected soon, but hopefully this atleast fixes the issue you're having so you can start getting basic functionality working.

Seems to be working for me, thank you!
