### ISSUE TITLE
When Subscriber joins server, the resub message appears. Every time

### ISSUE THREAD

**Issue by TheFrodo** [Dessie0/TwitchMinecraftSync#5]
If you sync with Twitch and then always join the server always comes that you have Resubt, although you have not. That Annoying a little

here the twitchdata: https://pastebin.com/EGe7rNzU

**Comment by Dessie0** [comment]
@TheFrodo Hm, maybe delete the twitchdata.yml and restart the server? I've never had that happen before.

**Comment by TheFrodo** [comment]
> @TheFrodo Hm, maybe delete the twitchdata.yml and restart the server? I've never had that happen before.

Heii, i will try this later when i'm at home. Then i will give you feedback if this works

**Comment by TheFrodo** [comment]
Hey sorry for not getting back to you. I had a little much around the ears.

I deleted twitchdata.yml and restarted the server. Unfortunately the problem is still there. :/

**Comment by TheFrodo** [comment]
Hello @Dessie0,
I wanted to check the current status. Is there soon an update of the plugin. I have not found an alternative yet, and would also like to support the plugin.

**Comment by Dessie0** [comment]
Oh wow, so sorry I didn't get back to you. I just replicated the issue so I'll push a fix hopefully in the coming hours.

**Comment by Dessie0** [comment]
I've updated the [plugin](https://github.com/Dessie0/TwitchMinecraftSync/releases/tag/v1.2.3), but unfortunately this issue isn't something that can be resolved. Twitch recently forced all applications to move to their new Helix API from Kraken. However, while Kraken offered fields for subscription expiration dates and streaks, Helix does not. This means the plugin has no way to determine whether someone resubscribed, and can only tell if they are currently subscribed. 

As the temporary work around, resubscribe groups and commands are always ran when someone joins. I have a thread open on the feedback website for Twitch asking for them to re-add these fields so resubscribe commands can be properly re-implemented. You can find that thread [here](https://twitch.uservoice.com/forums/310213-developers/suggestions/44874949-re-add-created-at-streak-and-or-expires-to-check) if you wish to upvote it. 

As a temporary fix to your problem, set all of the `resubscribe` commands to []. Should look something like this:
```yml
resubscribe:
  role: "Subscriber"
  commands: []
```

Hopefully Twitch will listen to that suggestion, but they usually take forever to do anything, so we're stuck with this for now.

**Comment by TheFrodo** [comment]
Hey, no problem at all.

I also voted for it on Twitch once. I will try that out and give you feedback :) 
If you keep coding the plugin it would be a cool idea to publish it on Spigot as well. I think many are looking for such a plugin and there is just no good one on the market.

**Comment by Dessie0** [comment]
@TheFrodo It's an interesting idea, and something I've certainly thought about doing. For some reason I feel as if this plugin does lack some features and configuration that would be somewhat necessary for it to be in the public marketplace. But I'm not sure honestly.

**Comment by TheFrodo** [comment]
ahh, does this plugin won't work anymore for 1.18?

`[20:45:31] [Server thread/ERROR]: Could not load 'plugins/TwitchMinecraftSync-1.2.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.19
	at org.bukkit.craftbukkit.v1_18_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:375) ~[paper-1.18.2.jar:git-Paper-386]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-386]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by Dessie0** [comment]
@TheFrodo Generally I make all my plugins support the latest version of Minecraft. I suppose this one wouldn't be too difficult to backport all the way to 1.8. I'll see what I can do.

**Comment by TheFrodo** [comment]
No Problem, I had just wondered. I just don't want to upgrade to 1.19 yet because it still runs a bit unstable.

**Comment by Dessie0** [comment]
@TheFrodo Alright, [this](https://github.com/Dessie0/TwitchMinecraftSync/releases/tag/v1.2.4) version should support Minecraft 1.8.8 -> 1.19.2. I tested 1.18.2, seemed to work. If you find any issues I'll make sure to fix those. 

I completely understand not wanting to update to 1.19. When I was testing this plugin for versions like 1.8 and 1.12 I was pretty amazed at how quickly those versions start compared to 1.19.

**Comment by TheFrodo** [comment]
So I tested it and it works without any problems. Thanks for your help. Drop your PayPal link please <3

**Comment by Dessie0** [comment]
@TheFrodo [Here](https://www.paypal.com/paypalme/dessie0) it is, I appreciate anything you send, as it's more than generous <3
