### ISSUE TITLE
Feature Request | NonSubscriber Role

### ISSUE THREAD

**Issue by ghost** [Dessie0/TwitchMinecraftSync#7]
First thx for this awesome plugin!!

Is there any possibility to set a config variable for a default role, so there is a possibility to set a role to a person that is only a viewer oder follower? With this u will be able to set a lot of things like abilities to build for nonsubs, but subs get's access to special rewarding plugins.

I'll hope u integrate something like that.

**Comment by Dessie0** [comment]
@ExXxO Currently the plugin doesn't track followers, for your default roles you should just use your group manager (i.e, LuckPerms, PermissionsEx, etc). And then create the groups with those plugins so that the plugin grants them the rewards when they subscribe.
