### ISSUE TITLE
VIP and Mods?

### ISSUE THREAD

**Issue by thelitsune** [Dessie0/TwitchMinecraftSync#8]
Is there a way to also sync VIP and Mods to a server and is there a way to limit a server to only Tier 3 subs? I have been trying to figure this out for a while and so far I have not been able to get it to work. Also does this work with any minecraft server or is Fabric/Forge/Whatever required? Thanks!

**Comment by Dessie0** [comment]
Unfortunately, no, the plugin currently isn't able to sync VIP, Mod, Follower, statuses. Only subscriptions for now. 

Yes, there are ways to limit the server to tier 3, but the plugin itself isn't enough to do something like that. The way I've prevented non-subs from joining in the past (which, you could do for all non-subs, tier 1, and tier 2 subs) is spawn everyone inside an in-es capable box. Then, when the plugin syncs someone as tier 3, you can teleport them outside the box. Then, of course, you can teleport them back inside that box if you want to remove their access to the server when their subscription expires. EssentialsX and EssentialsXSpawn are the plugins I've done it with, but I'm sure there's other alternatives you could use. 

Fabric or Forge aren't required. As long as your server is running Spigot (or can run Spigot plugins), and you have [Vault](https://www.spigotmc.org/resources/vault.34315/) installed, the plugin should work fine.

**Comment by thelitsune** [comment]
understood and hey thanks for the quick response! Hopefully ill find a good solution for the mods/vip/admins. Setting up twitch integrations and api is a pain xD

**Comment by Dessie0** [comment]
Yeah... I'm sure syncing those could be added to this plugin, I just don't really have the time to do it. I know people have used DiscordSRV in the past to do it, but of course that means people linking their Discords and you'd still have to micromanage the roles there.

**Comment by thelitsune** [comment]
I totally understand. If I was better at programming i would probably work on it myself. I can manage to do a few things myself but I never got good at Java. Thanks for all of the help and ideas though and best of luck to you!
