### ISSUE TITLE
Problem with twitchmcsync.com domain

### ISSUE THREAD

**Issue by tommasov03** [Dessie0/TwitchMinecraftSync#9]
Recently the twitchmcsync.com domain has expired, I understand that you no longer want/can maintain this service, I was wondering if it was possible to have the backend code in order to continue using this plugin. I await a response, thanks for your availability.
![Screenshot 2024-02-21 180641](https://github.com/Dessie0/TwitchMinecraftSync/assets/110355739/fd0e96db-7762-44d7-b46b-3061962e5e71)

**Comment by Dessie0** [comment]
The website should be back up now.

**Comment by tommasov03** [comment]
Perfect! Thank you very much and sorry for the inconvenience.
